server:
  port: 8081

spring:
  application:
    name: service-example
  config:
    import: optional:nacos:localhost:8848
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

logging:
  level:
    com.example: DEBUG
